### ISSUE TITLE
The issue that occurred during running KOBAS.

### ISSUE THREAD

**Issue by yweii** [xmao/kobas#6]
Hello,

Thank you for creating such a convenient tool for enrichment analysis.

However, I encountered a problem when performing KEGG pathway enrichment analysis of differentially expressed genes in rice. Since the web version has limitations on the number of genes, I ran the analysis locally using KOBAS installed on the school cluster. I was able to run the human example data successfully.

The first step was annotation. Since the local version does not support id:gene_symbol (my gene name example: Os10g0497300), I chose to annotate online (Plants / Monocots / Oryza sativa japonica (Japanese rice)(RAPDB)), resulting in the file: anno_seq.tsv. The file anno_seq.tsv was downloaded from kobas website.

The second step was to run the identification command, which resulted in an error.
identify.py -f anno_seq.tsv -o identifyout -q /public/home/wyang/biosofts/kobas/ftp.cbi.pku.edu.cn/pub/KOBAS_3.0_DOWNLOAD/sqlite3 -y /public/home/wyang/biosofts/kobas/ftp.cbi.pku.edu.cn/pub/KOBAS_3.0_DOWNLOAD/seq_pep

Traceback (most recent call last):
  File "/public/home/software/opt/bio/software/kobas/3.0//scripts/identify.py", line 3, in <module>
    from kobas.scripts import identify
  File "/public/home/software/opt/bio/software/kobas/3.0/src/kobas/scripts/identify.py", line 189, in <module>
    bdistr = discover.distr_from_default(opt.bgfile, db, speciesdb, abbr, opt.cutoff, idmapping)
  File "/public/home/software/opt/bio/software/kobas/3.0/src/kobas/discover.py", line 119, in distr_from_default
    dblink_ids = [dblink_id[0] for dblink_id in speciesdb.dblink_ids_from_gid(gid['gid'], idmapping)]
TypeError: 'NoneType' object is not iterable

How can I solve this issue? We will actively cite such a convenient software!

**Comment by binmao** [comment]
I have got the message ,thank you!     您发给我的信件已经收到。
